import { ChevronLeftIcon, ElipsisVerticalIcon } from "@/icons";
import { Metadata } from "next";
import Link from "next/link";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ChatLayout({ children }: { children: ReactNode }) {
  return (
    <div className="flex flex-col h-dvh overflow-hidden">
      <nav className="sticky top-0 navbar gap-4 shadow-lg">
        <Link href="/">
          <ChevronLeftIcon color="white" />
        </Link>
        <div className="flex-1 flex justify-between">
          <div className="avatar">
            <div className="w-8 rounded-full">
              <img
                src="https://daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg"
                alt="avatar"
              />
            </div>
          </div>
          <button type="button">
            <ElipsisVerticalIcon />
          </button>
        </div>
      </nav>
      {children}
    </div>
  );
}
